remote_theme: pmarsceill/just-the-docs

title: fgo-guides
description: >- # this means to ignore newlines until "baseurl:"
  Guides for FGO Events
baseurl: "/fgo-guides" # the subpath of your site, e.g. /blog
url: "https://enshael.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: enshael