remote_theme: pmarsceill/just-the-docs

title: fgo-guides
description: >- # this means to ignore newlines until "baseurl:"
  Guides for FGO Events
baseurl: "/fgo-guides" # the subpath of your site, e.g. /blog
url: "https://r-grandorder.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: r-grandorder
aux_links:
  "For any issues, report on Github":
    - "https://github.com/r-grandorder/fgo-guides/issues"

ga_tracking: G-490C572XSX
ga_tracking_anonymize_ip: true

callouts:
  warning:
    title: Warning
    color: red
  info:
    title: Info
    color: blue

#plugins:
#  - jekyll-seo-tag
#  - jekyll-github-metadata
#  - jekyll-include-cache